//! SC-W5-079 – Shared event correlation ids for cross-contract tracing.
//!
//! This module provides a `CorrelationId` type and associated functions for
//! propagating a shared correlation identifier across contract boundaries.
//! Backend consumers use the correlation ID to trace a single workflow (e.g.,
//! an SLA calculation that triggers a payment settlement) across events
//! emitted by multiple contracts.
//!
//! # Design
//!
//! A `CorrelationId` is a `u64` value that is:
//! - Generated by the entry-point contract (usually the SLA calculator)
//! - Passed as an argument to downstream contract calls
//! - Emitted in every event payload that is part of the same logical workflow
//!
//! # The home of the correlation ID
//!
//! The correlation ID is carried in the `set_int` (settlement intent) event
//! payload as a trailing `correlation_id` field — see `event_schema.rs` §
//! `set_int` (#566). Topics never carry it: the 3-topic layout
//! `(name, version, context)` is fixed by `event_schema.rs`, and the old
//! `correlation_event_topics` helper that accepted a `correlation_id` it
//! ignored has been removed (#565).
//!
//! # Integration
//!
//! The SLA calculator's `calculate_sla` generates a correlation ID from the
//! outage_id and ledger sequence, then includes it in the `set_int` event
//! payload and any downstream calls.
//!
//! Downstream contracts (payment escrow, settlement) accept the correlation
//! ID as a parameter and include it in their own events.

use alloc::string::ToString;
use soroban_sdk::{Env, Symbol};

/// Opaque correlation identifier for tracing workflows across contracts.
///
/// A `CorrelationId` is a `u64` that uniquely identifies a logical workflow
/// spanning one or more contract calls.  It is deterministic for a given
/// (outage_id, ledger_sequence) pair so that backends can re-derive it.
pub type CorrelationId = u64;

/// Generates a deterministic correlation ID for an (outage, ledger) pair.
///
/// The outage symbol's string bytes are hashed with FNV-1a and mixed with the
/// ledger sequence so that:
///
/// - distinct outages submitted in the same ledger always receive distinct
///   ids (SC-W5-079, #564), and
/// - repeating the same outage in the same ledger still reproduces the
///   identical id, preserving the replay semantics backends rely on.
///
/// The symbol is hashed via its `ToString` representation (Symbol bytes are
/// not directly accessible in Soroban SDK 21.x), so the result is
/// deterministic and reproducible off-chain by consumers that apply the same
/// FNV-1a mixing over the outage string and ledger sequence.
pub fn generate_correlation_id(_env: &Env, outage_id: &Symbol, ledger_sequence: u32) -> CorrelationId {
    // FNV-1a over the outage symbol bytes, then the ledger sequence.
    let mut hash: u64 = 0xcbf29ce484222325; // FNV-1a offset basis
    for byte in outage_id.to_string().as_bytes() {
        hash ^= u64::from(*byte);
        hash = hash.wrapping_mul(0x100000001b3); // FNV-1a prime
    }
    hash ^= (u64::from(ledger_sequence) << 32) | u64::from(ledger_sequence);
    hash = hash.wrapping_mul(0x100000001b3); // FNV-1a prime
    hash
}

#[cfg(test)]
mod tests {
    use super::*;
    use soroban_sdk::Env;

    #[test]
    fn test_correlation_id_is_deterministic() {
        let env = Env::default();
        let outage = Symbol::new(&env, "OUT001");
        let id1 = generate_correlation_id(&env, &outage, 42);
        let id2 = generate_correlation_id(&env, &outage, 42);
        assert_eq!(id1, id2);
    }

    #[test]
    fn test_correlation_id_changes_with_ledger_sequence() {
        let env = Env::default();
        let outage = Symbol::new(&env, "OUT001");
        // Different ledger sequences must produce different IDs
        let id_seq1 = generate_correlation_id(&env, &outage, 42);
        let id_seq2 = generate_correlation_id(&env, &outage, 100);
        assert_ne!(id_seq1, id_seq2);
    }

    #[test]
    fn test_correlation_id_is_non_zero() {
        let env = Env::default();
        let id = generate_correlation_id(&env, &Symbol::new(&env, "OUT001"), 1);
        assert_ne!(id, 0, "Correlation ID should not be zero");
    }

    #[test]
    fn test_correlation_id_distinct_ledger_sequences() {
        let env = Env::default();
        let outage = Symbol::new(&env, "OUT001");
        // Verify that different ledger sequences produce distinct outputs
        let id1 = generate_correlation_id(&env, &outage, 1);
        let id2 = generate_correlation_id(&env, &outage, 2);
        let id3 = generate_correlation_id(&env, &outage, 3);
        assert_ne!(id1, id2);
        assert_ne!(id2, id3);
        assert_ne!(id1, id3);
    }

    #[test]
    fn test_distinct_outages_in_same_ledger_never_collide() {
        let env = Env::default();
        // #564 – two different outages submitted in the same ledger must never
        // share a correlation id, or backends would join unrelated incidents.
        let outage_a = Symbol::new(&env, "SF001");
        let outage_b = Symbol::new(&env, "SF002");
        let id_a = generate_correlation_id(&env, &outage_a, 42);
        let id_b = generate_correlation_id(&env, &outage_b, 42);
        assert_ne!(
            id_a, id_b,
            "distinct outages in the same ledger must not share an id"
        );
    }

    #[test]
    fn test_same_outage_in_same_ledger_still_collides() {
        let env = Env::default();
        // #564 – replaying the same outage in the same ledger reproduces the
        // same id, preserving the determinism backends re-derive from.
        let outage = Symbol::new(&env, "SF001");
        let id1 = generate_correlation_id(&env, &outage, 42);
        let id2 = generate_correlation_id(&env, &outage, 42);
        assert_eq!(
            id1, id2,
            "same outage in the same ledger must reproduce the same id"
        );
    }

    #[test]
    fn test_correlation_id_long_outage_id() {
        let env = Env::default();
        let long_outage = Symbol::new(&env, "INC_2024_03_15_ABCDEF123456");
        let id = generate_correlation_id(&env, &long_outage, 99);
        assert_ne!(id, 0);
    }

    #[test]
    fn test_correlation_id_empty_symbol_still_hashes() {
        let env = Env::default();
        // Edge case: very short symbol
        let short = Symbol::new(&env, "X");
        let id = generate_correlation_id(&env, &short, 1);
        assert_ne!(id, 0);
    }
}
